### ISSUE TITLE
Email account password encryption

### ISSUE THREAD

**Issue by kao98** [cozy/cozy-emails#256] opened 2015-03-31 14:20 UTC
As I was testing Cozy, I was surprised to see the password for my email account using the `Data Browser` app.

Shouldn't it be encrypted?
Couldn't it be encrypted?

I think the cozy controller should provide a secure encryption method, using the user password maybe, to cozy apps to allow encryption of sensitive data. Maybe something is already planned?

**Comment by frankrousseau** [comment] 2015-03-31 14:28
In fact the problem is that the Data Browser has access to the data. Authorized apps are allowed to unencrypt it. The password is properly encrypted in the database, but the app shouldn't display it. 

If you have any idea about what we could do to improve this, it would be great.

**Comment by kao98** [comment] 2015-03-31 14:41
Hmm ... that make sense.

Is it possible to authorize only the owner of the data to decrypt it? 
I think that's not really compatible with the current architecture of Cozy and the way datas are managed.
But maybe passwords (and all encrypted data) should not be shared between apps and be accessible only by the one that encrypted it?

As a developer I love the way datas are managed / shared.
As a user, I would prefer my sensitive datas weren't shared at all.

**Comment by kao98** [comment] 2015-04-17 14:14
Hi,

Is there an open discussion about that question? On the forum? Elsewhere?

**Comment by frankrousseau** [comment] 2015-04-17 14:34
I think it's the only place where we talk about it. It would be nice to open a thread on the forum about it.

**Comment by kao98** [comment] 2015-04-17 14:57
Thread opened (in French) here:
https://forum.cozy.io/t/password-des-comptes-email-accessible-en-clair/513


2015-04-17 16:34 GMT+02:00 Frank Rousseau <notifications@github.com>:

**Comment by poupotte** [comment] 2015-04-20 07:02
I close this issue, we can continue  discussion in forum thread.

**Closed by poupotte** 2015-04-20 07:02 UTC
Labels: question
