### ISSUE TITLE
Message deletion leads to an error

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#123] opened 2015-01-26 12:02 UTC
When I delete several messages simultaneously, it leads to that error on the server side:

```
EROR errorhandler [Error: modifying UID is not possible]
[Mon, 26 Jan 2015 11:54:32 GMT] - PATCH /message/f791e138a4ea2ef42fae5e07f9208533 - 500 - 18.943 ms -  -
EROR errorhandler [Error: modifying UID is not possible]
[Mon, 26 Jan 2015 11:54:32 GMT] - PATCH /message/f791e138a4ea2ef42fae5e07f9208267 - 500 - 21.125 ms -  -
EROR errorhandler [Error: modifying UID is not possible]
[Mon, 26 Jan 2015 11:54:32 GMT] - PATCH /message/f791e138a4ea2ef42fae5e07f92073b1 - 500 - 15.321 ms -  -
EROR errorhandler [Error: modifying UID is not possible]
[Mon, 26 Jan 2015 11:54:32 GMT] - PATCH /message/f791e138a4ea2ef42fae5e07f9206e45 - 500 - 13.128 ms -  -
EROR errorhandler [Error: modifying UID is not possible]
[Mon, 26 Jan 2015 11:54:32 GMT] - PATCH /message/f791e138a4ea2ef42fae5e07f9206516 - 500 - 7.880 ms -  -
```

**Comment by poupotte** [comment] 2015-01-27 12:05
This issue is probably a duplicate of #77

**Comment by aenario** [comment] 2015-03-23 14:50
link #132

**Closed** 2015-04-10 14:13 UTC
Labels: 5 - Published, bug, duplicate
