### ISSUE TITLE
Deleting several emails should remove them instantly from the list

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#413] opened 2015-05-03 21:15 UTC
When I delete several emails, the deletion works but the experience is poor. It very long to remove every emails.

**Comment by clochix** [comment] 2015-05-04 15:14
How do you delete messages from the list ? When I select some messages and click on the trash in toolbar, they are immediately removed from the list (deleting message on the server takes more time, so the confirmation notification is displayed a few seconds later).

Deleting them with “delete conversation” in action menu seems broken.

**Comment by frankrousseau** [comment] 2015-05-04 16:18
I select something like 20 messages and click on the trash button.

**Comment by poupotte** [comment] 2015-05-05 10:04
Mmmm... I don't arrive to reproduce this issue. 
@frankrousseau , You have this behavior at each deletion or it's a random behavior ?

**Comment by frankrousseau** [comment] 2015-05-06 08:08
You should try on an online Cozy. Everything works well at the beginning but the messages come back then are deleted.

**Comment by poupotte** [comment] 2015-05-06 08:56
Ah ok, at the beginning you see your messages disappear but sometimes its reappear. Thanks for precision.

I can reproduce it. It's probably due to requests crossing.

**Comment by clochix** [comment] 2015-05-27 14:44
I'm still unable to reproduce. @frankrousseau, do you still have this problem with the last version of the application ?

**Comment by frankrousseau** [comment] 2015-05-27 17:52
Yeah the messages still come back when I delete too much messages in a row.

**Comment by poupotte** [comment] 2015-06-15 07:36
It should be fixed in the new version. @frankrousseau , can you test it on your Cozy ?

**Closed** 2015-07-02 08:42 UTC
Labels: 5 - Published, bug
