### ISSUE TITLE
Menu bar inaccessible after "new mail"

### ISSUE THREAD

**Issue by christi9n** [cozy/cozy-emails#369] opened 2015-04-22 20:26 UTC
Everything is going on well during navigation in the whole interface.
Except after clicking on "New mail", me nu bar then disapears (Iceweasel 37.0.2).
I attach screen capture.

![capture du 2015-04-22 22 25 13](https://cloud.githubusercontent.com/assets/11626946/7284507/78e0ec4c-e93e-11e4-9dc8-f168940dbf33.png)

and Many thanks ;o)

**Comment by frankrousseau** [comment] 2015-04-22 20:42
I experience the same problem and it's very annoying. 

@poupotte do you think we can add it to the current sprint?

**Comment by poupotte** [comment] 2015-04-23 14:10
This issue is a duplicate of #328. @m4dz works on layout in the current sprint, this issue should be fixed with his refactoring.

**Comment by poupotte** [comment] 2015-05-04 07:27
I close this issue, you can see development on #328.

**Closed by poupotte** 2015-05-04 07:27 UTC
Labels: bug, duplicate
