### ISSUE TITLE
[GAF] Spinner be spinnin'

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-emails#226] opened 2015-03-23 14:25 UTC
On Miss Bnjbvr's cozy instance, there are 2 mailboxes: one Gmail account and one Hotmail account. When starting the app, the "sync" button is off and there's a spinner instead, spinning all the time, it appears.

I've tried restarting the app, force-reloading the client, it is still spinning.

Logs show IMAP REFRESH actions for a while (nothing weird), but after some point, nothing shows up anymore and the sync button is still spinning.

I've made sure that identifiers and passwords were correct, by using the "test connection" button, which says that everything is fine, on that side.

Moreover, at start up, there is some error showing up, but its message is quite obscure:
```                                                                                                     
EROR imap:pool active connection closed undefined                                                                                                    
EROR imap:reporter Error: connection was closed                                                                                                      
    at ImapPool._onActiveClose (/usr/local/cozy/apps/emails/build/server/imap/pool.js:177:30)                                                        
    at Connection.g (events.js:180:16)                                                                                                               
    at Connection.emit (events.js:95:17)                                                                                                             
    at Socket.<anonymous> (/usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:155:10)                                                   
    at Socket.g (events.js:180:16)                                                                                                                   
    at Socket.emit (events.js:117:20)                                                                                                                
    at TCP.close (net.js:466:12)     
```

And the spinner is still spinning.

**Comment by jsilvestre** [comment] 2015-03-26 07:18
So apparently this bug is not a bug, as you confirmed it just takes a very long time. I opened a new issue (https://github.com/cozy/cozy-emails/issues/233) to improve the loading indicator, and will close this one if it's okay with you.

**Closed** 2015-04-10 14:13 UTC
Labels: 5 - Published, bug
