### ISSUE TITLE
Wrong error message on connection timeout

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#561] opened 2015-07-15 14:25 UTC
The user get the following error:
```
{"name":"AccountConfigError","field":"imapTLS","stack":"","error":true}
```

Looking at server logs, it seems to be a timeout while trying to connect to IMAP server:
```
EROR +0000 models:account CANT REFRESH ACCOUNT xxxx  { [AccountConfigError: on field 'imapTLS'] name: 'AccountConfigError', field: 'imapTLS', message: 'on field \'imapTLS\'', stack: '', original: { [Error: Timed out while authenticating with server] source: 'timeout-auth' } } 
```

We should probably try to display a more user friendly error message.

**Comment by poupotte** [comment] 2015-09-08 14:04
Duplicate of #350

**Closed by poupotte** 2015-09-08 14:04 UTC
Labels: 1 - Todo, bug
