### ISSUE TITLE
Application keeps crashing and detected as "broken"' by home

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#668] opened 2015-10-22 15:23 UTC
Unfortunately, I cannot provide relevant log.

**Comment by ZeHiro** [comment] 2015-10-23 08:10
@clochix 
This problem occured again. 
Here is what I observed: 
```top -u cozy-emails``` 
returns no process

```cozy-monitor status``` says emails is down

```curl localhost -p 9125``` returns 301, but it can be due to the fact that iam not authentified

**Comment by ZeHiro** [comment] 2015-10-23 08:47
In fact the way to get the "broken" app is as following: 
The app is down
I stop the app
The application is said as broken (with the notification "Install fail")

**Comment by ZeHiro** [comment] 2015-10-23 09:10
Getting more info, if it can help: 

In the proxy log: 

```
[2015-10-23 11:03:59:440] error - app:error | Error: connect ECONNREFUSED
[2015-10-23 11:03:59:449] error - app:error | Error: Error: connect ECONNREFUSED
    at ProxyServer.<anonymous> (/usr/local/cozy/apps/proxy/build/server/lib/proxy.js:37:11)
    at ProxyServer.emit (/usr/local/cozy/apps/proxy/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/usr/local/cozy/apps/proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:140:16)
    at ClientRequest.EventEmitter.emit (events.js:117:20)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)
[2015-10-23 11:05:34:801] error - app:error | Error: socket hang up
[2015-10-23 11:05:34:807] error - app:error | Error: Error: socket hang up
    at ProxyServer.<anonymous> (/usr/local/cozy/apps/proxy/build/server/lib/proxy.js:37:11)
    at ProxyServer.emit (/usr/local/cozy/apps/proxy/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/usr/local/cozy/apps/proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:140:16)
    at ClientRequest.EventEmitter.emit (events.js:117:20)
    at Socket.socketCloseListener (http.js:1522:9)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:465:12)
```

**Comment by frankrousseau** [comment] 2015-10-23 11:03
It looks like your CouchDB or DataSystem is down. Do your other apps are working?

**Comment by ZeHiro** [comment] 2015-10-23 11:26
Yes they are ...

**Comment by ZeHiro** [comment] 2015-10-23 13:58
OK. After checking syslog, it appears the app is filled by the system.  (@clochix can explain)

**Comment by frankrousseau** [comment] 2015-10-24 13:20
Thank you for this additional information.Which app are you talking about? Emails?

**Comment by ZeHiro** [comment] 2015-10-24 15:57
Emails. I got several out of memory kills, on emails. On a rpi2 (1GB ram) this smth which cn be expected. Could there be a memory leak serverside?

**Comment by ZeHiro** [comment] 2015-10-27 10:35
@clochix 
I tmore and more think there is a problem with memory. After a restart of emails app (after oom kill) of 150 to 200 MB in the memory consumption.

**Comment by clochix** [comment] 2015-10-27 11:06
@aenario are you aware of memory leaks in the application ?

**Comment by aenario** [comment] 2015-10-27 16:52
I am not aware of any memory leak, but there always could be some. 

Moreover,  the "recent" changes (late spring) were all about placing all accounts and mailboxes in RAM so we have a base usage with lower spikes and more predictable performances, but its means the base RAM usage do increase proportionally to number of mailboxes/accounts.  

@ZeHiro, if the raise to 250MB is immediate (in less than 3s after app start), it might be caused by too many accounts/mailboxes to be handled on a RASPI (and we will be in big trouble). If it climbs more slowly, there might be a memory leak in the refresh process (and we "just" need to track it down).

**Comment by ZeHiro** [comment] 2015-11-03 14:13
@aenario 
in fact it is the whole stack which is growing. As emails is always at least 150MB, it is usually the one which get kicked. In fact I have : 
- proxy: 100MB
- home: 100MB
- ds: 150-250MB
- 2 couch.js (100MB each)
- 1 beam.smp 100MB

which leavec 250/300MB for "real apps". As emails require quite a lot of memory, even more on update of mailboxes (i have 3 on my cozy). It is usually the one kicked.

**Comment by graebermedien** [comment] 2016-08-09 18:55
Hi Folks,

getting error on emails update:
`
 Error: Error: socket hang up
    at module.exports.makeError (/usr/local/lib/node_modules/cozy-monitor/lib/helpers.js:90:12)
    at /usr/local/lib/node_modules/cozy-monitor/lib/application.js:347:31
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/cozy-monitor/node_modules/request-json-light/main.js:113:12)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketOnEnd [as onend] (http.js:1568:9)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
`

Protocol:

`[2016-08-09 20:50:25:86] error - app:error | Error: app broken
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/controllers/applications.js:43:15
    at AppManager.ensureStarted (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/lib/app_manager.js:35:16)
    at forwardRequest (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/controllers/applications.js:38:21)
    at module.exports.app (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/controllers/applications.js:69:10)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at module.exports.isAuthenticated (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/middlewares/authentication.js:151:12)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/americano/node_modules/express/lib/router/route.js:91:3)`

Anything related to this topic or new bug?!

-> Happens on fresh install of Debian jessie 64Bit

any suggestions to geht the mail app working?

Home Screen on clicking the Mail App (Crashed) shows the following:

Die Abhängigkeiten der App onnten nicht installiert werden.

: Error at /usr/local/cozy/apps/home/node_modules/cozy-home/build/server/lib/paas.js:162:21 at parseBody (/usr/local/cozy/apps/home/node_modules/cozy-home/node_modules/cozy-clients/node_modules/request-json/main.js:35:12) at Request._callback (/usr/local/cozy/apps/home/node_modules/cozy-home/node_modules/cozy-clients/node_modules/request-json/main.js:96:18) at Request.self.callback (/usr/local/cozy/apps/home/node_modules/cozy-home/node_modules/cozy-clients/node_modules/request-json/node_modules/request/request.js:121:22) at Request.emit (events.js:98:17) at Request.<anonymous> (/usr/local/cozy/apps/home/node_modules/cozy-home/node_modules/cozy-clients/node_modules/request-json/node_modules/request/request.js:978:14) at Request.emit (events.js:117:20) at IncomingMessage.<anonymous> (/usr/local/cozy/apps/home/node_modules/cozy-home/node_modules/cozy-clients/node_modules/request-json/node_modules/request/request.js:929:12) at IncomingMessage.emit (events.js:117:20) at _stream_readable.js:929:16

**Comment by poupotte** [comment] 2016-08-19 07:14
This issue is not relevant anymore because we're working on a new Emails version.

**Closed by poupotte** 2016-08-19 07:14 UTC
Labels: bug
